{% set name = "grit" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/manish59/grit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 40c0ad8652a05056aa8eac7662c23d68e67a86343ef588b397f46221c840121d

build:
  number: 0
  script: cargo install --locked --root $PREFIX --path .

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - rust
  run: []

test:
  commands:
    - grit --version

about:
  home: https://github.com/manish59/grit
  license: MIT
  license_file: LICENSE
  summary: "GRIT: Genomic Range Interval Toolkit"
  description: |
    GRIT (Genomic Range Interval Toolkit) is a high-performance toolkit for
    genomic interval operations. Supports intersect, merge, sort, subtract,
    closest, coverage, slop, complement, genomecov, jaccard, multiinter, and
    window commands.
  dev_url: https://github.com/manish59/grit

extra:
  recipe-maintainers:
    - manish59
